// This file has been generated by Py++.

#include "boost/python.hpp"

#include "boost/python/suite/indexing/vector_indexing_suite.hpp"

#include "test.h"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(libtest_py){
    { //::std::vector< std::string >
        typedef bp::class_< std::vector< std::string > > vector_less__std_scope_string__greater__exposer_t;
        vector_less__std_scope_string__greater__exposer_t vector_less__std_scope_string__greater__exposer = vector_less__std_scope_string__greater__exposer_t( "vector_less__std_scope_string__greater_" );
        bp::scope vector_less__std_scope_string__greater__scope( vector_less__std_scope_string__greater__exposer );
        vector_less__std_scope_string__greater__exposer.def( bp::vector_indexing_suite< ::std::vector< std::string >, true >() );
    }

    bp::class_< Test >( "Test", bp::init< >() )    
        .def( 
            "GetAge"
            , (int ( ::Test::* )(  ) )( &::Test::GetAge ) )    
        .def( 
            "GetFriendSize"
            , (int ( ::Test::* )(  ) )( &::Test::GetFriendSize ) )    
        .def( 
            "PrintInfo"
            , (void ( ::Test::* )(  ) )( &::Test::PrintInfo ) )    
        .def_readwrite( "m_age_", &Test::m_age_ )    
        .def_readwrite( "m_friends_", &Test::m_friends_ );
}
